### ISSUE TITLE
clicking VS Code Desktop takes user to active window, does not create new session

### ISSUE THREAD

**Issue by ericpaulsen** [coder/vscode-coder#136]
consider the scenario where i have two workspaces, A & B. i already have an open window with an active SSH session for workspace A. when clicking `VS Code Desktop` on workspace B, i'm routed directly to the VS Code window for workspace A, and it does not create a new window for an SSH session.

current workaround is to manually create a new window in VS Code (File > New Window), but ideal UX is to auto-create new window for each new workspace SSH session.

**Comment by aslilac** [comment]
hmm...idk that this is something we even have control over, kinda feels like a vscode issue

**Comment by mambon2** [comment]
this used to work before, meaning it always opened a new window until today.

**Comment by aslilac** [comment]
oh, interesting. maybe it's a regression in the new version we just published then. 😬

**Comment by mambon2** [comment]
was that today?

**Comment by aslilac** [comment]
it was late in the day on friday

**Comment by mafredri** [comment]
Seems the new release is broken. Reverting to previous version works:

<img width="496" alt="image" src="https://github.com/coder/vscode-coder/assets/147409/d3a46125-861c-4bd1-9483-11181bd38743">

Here's a log:

```
[15:12:33.640] Log Level: 2
[15:12:33.654] VS Code version: 1.82.1
[15:12:33.654] Remote-SSH version: remote-ssh@0.106.4
[15:12:33.654] darwin arm64
[15:12:33.660] SSH Resolver called for "ssh-remote+coder-vscode--mafredri--w", attempt 1
[15:12:33.661] "remote.SSH.useLocalServer": true
[15:12:33.661] "remote.SSH.useExecServer": false
[15:12:33.661] "remote.SSH.path": undefined
[15:12:33.661] "remote.SSH.configFile": /Users/maf/.ssh/coder
[15:12:33.661] "remote.SSH.useFlock": true
[15:12:33.661] "remote.SSH.lockfilesInTmp": false
[15:12:33.661] "remote.SSH.localServerDownload": auto
[15:12:33.661] "remote.SSH.remoteServerListenOnSocket": false
[15:12:33.661] "remote.SSH.showLoginTerminal": false
[15:12:33.662] "remote.SSH.defaultExtensions": []
[15:12:33.662] "remote.SSH.loglevel": 2
[15:12:33.662] "remote.SSH.enableDynamicForwarding": true
[15:12:33.662] "remote.SSH.enableRemoteCommand": false
[15:12:33.662] "remote.SSH.serverPickPortsFromRange": {}
[15:12:33.662] "remote.SSH.serverInstallPath": {}
[15:12:33.665] SSH Resolver called for host: coder-vscode--mafredri--w
[15:12:33.665] Setting up SSH remote "coder-vscode--mafredri--w"
[15:12:33.666] Acquiring local install lock: <tmp>/vscode-remote-ssh-11fb96b2-install.lock
[15:12:33.667] Looking for existing server data file at /Users/maf/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-11fb96b2-6509174151d557a81c9d0b5f8a5a1e9274db5585-0.106.4/data.json
[15:12:33.667] Using commit id "6509174151d557a81c9d0b5f8a5a1e9274db5585" and quality "stable" for server
[15:12:33.669] Install and start server if needed
[15:12:33.670] PATH: <redacted>
[15:12:33.670] Checking ssh with "ssh -V"
[15:12:33.675] > OpenSSH_9.0p1, LibreSSL 3.3.6

[15:12:33.676] Using SSH config file "/Users/maf/.ssh/coder"
[15:12:33.677] askpass server listening on <tmp>/vscode-ssh-askpass-c342805eb5c609853f092fc365a9822c3991da02.sock
[15:12:33.677] Spawning local server with {"serverId":1,"ipcHandlePath":"<tmp>/vscode-ssh-askpass-f1d37ac66483b8c7f59a3abe0fc5de0e81a5dc1b.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","63231","-o","ConnectTimeout=15","-F","/Users/maf/.ssh/coder","coder-vscode--mafredri--w","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/maf/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-11fb96b2-6509174151d557a81c9d0b5f8a5a1e9274db5585-0.106.4/data.json"}
[15:12:33.677] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.G3RXMuZLUr/Listeners","SHELL":"/opt/homebrew/bin/zsh","DISPLAY":"/private/tmp/com.apple.launchd.c4gdoQpxhr/org.xquartz:0","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"<tmp>/vscode-ssh-askpass-c342805eb5c609853f092fc365a9822c3991da02.sock"}
[15:12:33.678] Spawned 8431
[15:12:33.754] > local-server-1> Running ssh connection command: "-v -T -D 63231 -o ConnectTimeout=15 -F /Users/maf/.ssh/coder coder-vscode--mafredri--w bash"
[15:12:33.756] > local-server-1> Spawned ssh, pid=8438
[15:12:33.759] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[15:12:33.764] stderr> zsh:1: no such file or directory: /Users/maf/Library/Application Support/Code/User/globalStorage/coder.coder-remote/bin/coder-darwin-arm64
[15:12:33.765] stderr> kex_exchange_identification: Connection closed by remote host
[15:12:33.765] stderr> Connection closed by UNKNOWN port 65535
[15:12:33.765] > local-server-1> ssh child died, shutting down
[15:12:33.767] Local server exit: 0
[15:12:33.768] Received install output: local-server-1> Running ssh connection command: "-v -T -D 63231 -o ConnectTimeout=15 -F /Users/maf/.ssh/coder coder-vscode--mafredri--w bash"
local-server-1> Spawned ssh, pid=8438
OpenSSH_9.0p1, LibreSSL 3.3.6
zsh:1: no such file or directory: /Users/maf/Library/Application Support/Code/User/globalStorage/coder.coder-remote/bin/coder-darwin-arm64
kex_exchange_identification: Connection closed by remote host
Connection closed by UNKNOWN port 65535
local-server-1> ssh child died, shutting down

[15:12:33.768] Failed to parse remote port from server output
[15:12:33.769] Resolver error: Error: 
	at g.Create (/Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:637879)
	at t.handleInstallOutput (/Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:635279)
	at e (/Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:695279)
	at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
	at async /Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:717117
	at async t.withShowDetailsEvent (/Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:720723)
	at async /Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:693700
	at async C (/Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:690170)
	at async t.resolveWithLocalServer (/Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:693291)
	at async C (/Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:714245)
	at async t.resolve (/Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:718119)
	at async /Users/maf/.vscode/extensions/ms-vscode-remote.remote-ssh-0.106.4/out/extension.js:2:901789
[15:12:33.771] ------
```

**Comment by mafredri** [comment]
Looks like this was broken by https://github.com/coder/vscode-coder/commit/f440f5eff40d22bcb614e20aa51e7df7a01ab9b7 and the check for settings values, they aren't empty strings if they're missing.

@mambon2 we'll fix this soon. For now another workaround is to set this in your VS Code settings:

```json
	"coder.tlsCertFile": "",
	"coder.tlsKeyFile": "",
	"coder.tlsCaFile": ""
```

**Comment by ericpaulsen** [comment]
fixed via https://github.com/coder/vscode-coder/commit/1af64868148a39e3dbf5f54df92321cc8e23d23d
