### ISSUE TITLE
Error launching workspace locall: Can't resolve hostname to Coder workspace container

### ISSUE THREAD

**Issue by pcgeek86** [coder/vscode-coder#67]
### Summary

Coder Remote VSCode extension throws error while attempting to connect to remote development environment.
In the VSCode logs, you can see that Coder is attempting to connect to a hostname that doesn't actually exist.

### Repro Steps

1. Run Coder v2 as Docker Container
2. Use Cloudflare Tunnels to forward a public hostname `ie. editor.mydomain.com` to Coder container
3. Connect to Coder web interface and create first user
4. Create a workspace template and workspace
5. Attempt to open the workspace in local VSCode
6. Observe error details below

**NOTE**: Connecting to the Coder workspace, using the web-based environment, works perfectly fine.

#### Server Environment

* Ubuntu 22.04 LTS
* Docker Engine version:latest
* Coder container [v0.19.2+7eb2c2f](https://github.com/coder/coder/commit/7eb2c2ff6d229619f88f41e9b2b185714a967619)

#### Client Environment

* MacOS Ventura
* VSCode 1.76.1
* Coder v0.1.13

### Expected Results

VSCode successfully opens Coder workspace locally.

### Actual Results

<img width="562" alt="Screenshot 2023-03-19 at 8 21 46 PM" src="https://user-images.githubusercontent.com/466713/226232799-c8a933e0-a2f9-491b-aba7-10e06271c8a6.png">
<img width="877" alt="Screenshot 2023-03-19 at 8 21 53 PM" src="https://user-images.githubusercontent.com/466713/226232811-443278ae-54c7-4500-a538-be9e31a2f52c.png">

```
[20:21:41.980] Log Level: 2
[20:21:41.984] VS Code version: 1.76.1
[20:21:41.984] Remote-SSH version: remote-ssh@0.98.0
[20:21:41.984] darwin x64
[20:21:47.448] SSH Resolver called for "ssh-remote+coder-vscode--trevor--trevor01", attempt 1
[20:21:47.448] "remote.SSH.useLocalServer": true
[20:21:47.448] "remote.SSH.path": undefined
[20:21:47.449] "remote.SSH.configFile": ~/.ssh/vscode-config
[20:21:47.449] "remote.SSH.useFlock": true
[20:21:47.449] "remote.SSH.lockfilesInTmp": false
[20:21:47.449] "remote.SSH.localServerDownload": auto
[20:21:47.450] "remote.SSH.remoteServerListenOnSocket": false
[20:21:47.450] "remote.SSH.showLoginTerminal": false
[20:21:47.450] "remote.SSH.defaultExtensions": ["gitpod.gitpod-remote-ssh"]
[20:21:47.450] "remote.SSH.loglevel": 2
[20:21:47.450] "remote.SSH.enableDynamicForwarding": true
[20:21:47.451] "remote.SSH.enableRemoteCommand": false
[20:21:47.451] "remote.SSH.serverPickPortsFromRange": {}
[20:21:47.451] "remote.SSH.serverInstallPath": {}
[20:21:47.454] SSH Resolver called for host: coder-vscode--trevor--trevor01
[20:21:47.455] Setting up SSH remote "coder-vscode--trevor--trevor01"
[20:21:47.458] Acquiring local install lock: /var/folders/bw/yc3krqjs11bdctkqj_clqf4c0000gn/T/vscode-remote-ssh-5514b554-install.lock
[20:21:47.459] Looking for existing server data file at /Users/trevor/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-5514b554-5e805b79fcb6ba4c2d23712967df89a089da575b-0.98.0/data.json
[20:21:47.460] Using commit id "5e805b79fcb6ba4c2d23712967df89a089da575b" and quality "stable" for server
[20:21:47.465] Install and start server if needed
[20:21:47.469] PATH: /usr/local/microsoft/powershell/7:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin
[20:21:47.469] Checking ssh with "ssh -V"
[20:21:47.475] > OpenSSH_9.0p1, LibreSSL 3.3.6

[20:21:47.477] Using SSH config file "/Users/trevor/.ssh/vscode-config"
[20:21:47.477] askpass server listening on /var/folders/bw/yc3krqjs11bdctkqj_clqf4c0000gn/T/vscode-ssh-askpass-8590af0b0811d93cba6cf619a91f4db8265d4eb3.sock
[20:21:47.478] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/bw/yc3krqjs11bdctkqj_clqf4c0000gn/T/vscode-ssh-askpass-ad9ca0ed08af24442e5d3863267cc3a984a1ebbd.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","52506","-o","ConnectTimeout=15","-F","/Users/trevor/.ssh/vscode-config","coder-vscode--trevor--trevor01","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/trevor/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-5514b554-5e805b79fcb6ba4c2d23712967df89a089da575b-0.98.0/data.json"}
[20:21:47.478] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.9s5lZKgmdO/Listeners","SHELL":"/usr/local/bin/pwsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/bw/yc3krqjs11bdctkqj_clqf4c0000gn/T/vscode-ssh-askpass-8590af0b0811d93cba6cf619a91f4db8265d4eb3.sock"}
[20:21:47.479] Spawned 99503
[20:21:47.624] > local-server-1> Running ssh connection command: "-v -T -D 52506 -o ConnectTimeout=15 -F /Users/trevor/.ssh/vscode-config coder-vscode--trevor--trevor01 bash"
[20:21:47.626] > local-server-1> Spawned ssh, pid=99507
[20:21:47.631] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[20:21:47.634] stderr> ssh: Could not resolve hostname coder-vscode--trevor--trevor01: nodename nor servname provided, or not known
[20:21:47.635] > local-server-1> ssh child died, shutting down
[20:21:47.639] Local server exit: 0
[20:21:47.639] Received install output: local-server-1> Running ssh connection command: "-v -T -D 52506 -o ConnectTimeout=15 -F /Users/trevor/.ssh/vscode-config coder-vscode--trevor--trevor01 bash"
local-server-1> Spawned ssh, pid=99507
OpenSSH_9.0p1, LibreSSL 3.3.6
ssh: Could not resolve hostname coder-vscode--trevor--trevor01: nodename nor servname provided, or not known
local-server-1> ssh child died, shutting down

[20:21:47.642] Resolver error: Error: Could not resolve hostname
	at m.Offline (/Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584439)
	at /Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:581669
	at t.handleInstallOutput (/Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:582037)
	at Object.e [as tryInstallWithLocalServer] (/Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:623670)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:643639
	at async t.withShowDetailsEvent (/Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359)
	at async /Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:622142
	at async C (/Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:618648)
	at async t.resolveWithLocalServer (/Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:621757)
	at async t.resolve (/Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644967)
	at async /Users/trevor/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839
[20:21:47.644] ------
```

**Comment by kylecarbs** [comment]
Hey @pcgeek86 :wave: This is odd... can you bring up the output panel for Coder? I'm not sure why we'd be trying to `mkdir` in your home.

**Comment by pcgeek86** [comment]
Hello @kylecarbs, here's the output I'm seeing for the Coder extension in VSCode. I replicated the same problem from my Windows 11 client workstation.

```
Using binName: coder-windows-amd64.exe
Using binPath: c:\Users\TrevorSullivan\scoop\apps\vscode\1.76.2\data\user-data\User\globalStorage\coder.coder-remote\bin\coder-windows-amd64.exe
Using ETag: 
Response status code: 200
Downloaded binary: c:\Users\TrevorSullivan\scoop\apps\vscode\1.76.2\data\user-data\User\globalStorage\coder.coder-remote\bin\coder-windows-amd64.exe
```

**Comment by kylecarbs** [comment]
Well let me write a test first before I fully confirm it ;p @pcgeek86

**Comment by pcgeek86** [comment]
> Well let me write a test first before I fully confirm it ;p @pcgeek86

Good plan! Will resolving the tilde correct the DNS error? It's trying to find a hostname with no DNS suffix on it, which is rather bizarre.

**Comment by kylecarbs** [comment]
@pcgeek86 to confirm this will work on your computer, can you try specifying a manual path to the SSH config instead of using `~`? I have a small fix, but would rather ensure it works on Windows before pushing.

**Comment by kylecarbs** [comment]
Although I'm about 99% sure it'll fix it ;p

**Comment by pcgeek86** [comment]
Confirmed working. Or at least, getting farther than before.

![image](https://user-images.githubusercontent.com/466713/226669888-d2672723-cf45-42ce-ae2d-08a9d13b4f51.png)

**Comment by pcgeek86** [comment]
Thanks man, I appreciate it!!! Hope everyone else benefits from the fix as well.

**Comment by pcgeek86** [comment]
New issue in logs:

```
2023/03/21 10:10:04 websocket Dial: failed to WebSocket dial: failed to send handshake request: Get "https://stun.l.google.com/derp": read tcp 10.0.0.48:54517->142.250.111.127:443: wsarecv: An existing connection was forcibly closed by the remote host., <nil>2023/03/21 10:10:08 websocket Dial: failed to WebSocket dial: failed to send handshake request: Get "https://stun.l.google.com/derp": read tcp 10.0.0.48:54519->142.250.111.127:443: wsarecv: An existing connection was forcibly closed by the remote host., <nil>2023/03/21 10:10:11 websocket Dial: failed to WebSocket dial: failed to send handshake request: Get "https://stun.l.google.com/derp": read tcp 10.0.0.48:54522->142.250.111.127:443: wsarecv: An existing connection was forcibly closed by the remote host., <nil>2023/03/21 10:10:15 websocket Dial: failed to WebSocket dial: failed to send handshake request: Get "https://stun.l.google.com/derp": read tcp 10.0.0.48:54545->142.250.111.127:443: wsarecv: An existing connection was forcibly closed by the remote host., <nil>
```

**Comment by kylecarbs** [comment]
And what version are you running?

**Comment by kylecarbs** [comment]
Humph, alright let me investigate this. We had a regression for some port-related DERP/STUN stuff in v0.19.0 but we patched it super quick, maybe something related to the STUN server slipped through.

I'll get an answer for you soon!

**Comment by pcgeek86** [comment]
Added you on Discord
