### ISSUE TITLE
Failing to connect when I open another folder

### ISSUE THREAD

**Issue by bpmct** [coder/vscode-coder#70]
Logs. `ssh coder.dev` works fine. I had to restart my workspace to connect

```sh
[12:21:23.389] Log Level: 2
[12:21:23.441] VS Code version: 1.76.2
[12:21:23.441] Remote-SSH version: remote-ssh@0.98.0
[12:21:23.441] darwin x64
[12:21:26.776] SSH Resolver called for "ssh-remote+coder-vscode--bpmct--dev", attempt 1
[12:21:26.777] "remote.SSH.useLocalServer": true
[12:21:26.777] "remote.SSH.path": undefined
[12:21:26.777] "remote.SSH.configFile": undefined
[12:21:26.778] "remote.SSH.useFlock": true
[12:21:26.778] "remote.SSH.lockfilesInTmp": false
[12:21:26.778] "remote.SSH.localServerDownload": auto
[12:21:26.778] "remote.SSH.remoteServerListenOnSocket": false
[12:21:26.778] "remote.SSH.showLoginTerminal": false
[12:21:26.779] "remote.SSH.defaultExtensions": []
[12:21:26.779] "remote.SSH.loglevel": 2
[12:21:26.779] "remote.SSH.enableDynamicForwarding": true
[12:21:26.779] "remote.SSH.enableRemoteCommand": false
[12:21:26.779] "remote.SSH.serverPickPortsFromRange": {}
[12:21:26.779] "remote.SSH.serverInstallPath": {}
[12:21:26.788] SSH Resolver called for host: coder-vscode--bpmct--dev
[12:21:26.788] Setting up SSH remote "coder-vscode--bpmct--dev"
[12:21:26.792] Acquiring local install lock: /var/folders/wz/rb67ppvj0rz0zmsrvmscdp6r0000gn/T/vscode-remote-ssh-d7dc8702-install.lock
[12:21:26.793] Looking for existing server data file at /Users/benpotter/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d7dc8702-ee2b180d582a7f601fa6ecfdad8d9fd269ab1884-0.98.0/data.json
[12:21:26.793] Using commit id "ee2b180d582a7f601fa6ecfdad8d9fd269ab1884" and quality "stable" for server
[12:21:26.797] Install and start server if needed
[12:21:26.803] PATH: /Users/benpotter/.deno/bin:/Users/benpotter/.nvm/versions/node/v14.19.3/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/usr/local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/sbin/:/Users/benpotter/go/bin
[12:21:26.803] Checking ssh with "ssh -V"
[12:21:26.810] > OpenSSH_9.0p1, LibreSSL 3.3.6

[12:21:26.814] askpass server listening on /var/folders/wz/rb67ppvj0rz0zmsrvmscdp6r0000gn/T/vscode-ssh-askpass-5d5f6d03c30335269acc63c15c379bfdbb94f0ab.sock
[12:21:26.814] Spawning local server with {"serverId":1,"ipcHandlePath":"/var/folders/wz/rb67ppvj0rz0zmsrvmscdp6r0000gn/T/vscode-ssh-askpass-0b61af1e01a08f0f5d43d502e4cd02d5b9c4c3d7.sock","sshCommand":"ssh","sshArgs":["-v","-T","-D","56162","-o","ConnectTimeout=15","coder-vscode--bpmct--dev","bash"],"serverDataFolderName":".vscode-server","dataFilePath":"/Users/benpotter/Library/Application Support/Code/User/globalStorage/ms-vscode-remote.remote-ssh/vscode-ssh-host-d7dc8702-ee2b180d582a7f601fa6ecfdad8d9fd269ab1884-0.98.0/data.json"}
[12:21:26.814] Local server env: {"SSH_AUTH_SOCK":"/private/tmp/com.apple.launchd.jmVGwd3a0M/Listeners","SHELL":"/bin/zsh","DISPLAY":"1","ELECTRON_RUN_AS_NODE":"1","SSH_ASKPASS":"/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/local-server/askpass.sh","VSCODE_SSH_ASKPASS_NODE":"/Applications/Visual Studio Code.app/Contents/Frameworks/Code Helper (Plugin).app/Contents/MacOS/Code Helper (Plugin)","VSCODE_SSH_ASKPASS_EXTRA_ARGS":"--ms-enable-electron-run-as-node","VSCODE_SSH_ASKPASS_MAIN":"/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/askpass-main.js","VSCODE_SSH_ASKPASS_HANDLE":"/var/folders/wz/rb67ppvj0rz0zmsrvmscdp6r0000gn/T/vscode-ssh-askpass-5d5f6d03c30335269acc63c15c379bfdbb94f0ab.sock"}
[12:21:26.815] Spawned 60079
[12:21:26.929] > local-server-1> Running ssh connection command: "-v -T -D 56162 -o ConnectTimeout=15 coder-vscode--bpmct--dev bash"
[12:21:26.931] > local-server-1> Spawned ssh, pid=60084
[12:21:26.935] stderr> OpenSSH_9.0p1, LibreSSL 3.3.6
[12:21:41.941] stderr> Connection timed out during banner exchange
[12:21:41.942] stderr> Connection to UNKNOWN port 65535 timed out
[12:21:41.942] > local-server-1> ssh child died, shutting down
[12:21:41.946] Local server exit: 0
[12:21:41.946] Received install output: local-server-1> Running ssh connection command: "-v -T -D 56162 -o ConnectTimeout=15 coder-vscode--bpmct--dev bash"
local-server-1> Spawned ssh, pid=60084
OpenSSH_9.0p1, LibreSSL 3.3.6
Connection timed out during banner exchange
Connection to UNKNOWN port 65535 timed out
local-server-1> ssh child died, shutting down

[12:21:41.949] Resolver error: Error: The connection timed out
	at m.Offline (/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:584439)
	at /Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:581823
	at t.handleInstallOutput (/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:582037)
	at Object.e [as tryInstallWithLocalServer] (/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:623670)
	at process.processTicksAndRejections (node:internal/process/task_queues:96:5)
	at async /Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:643639
	at async t.withShowDetailsEvent (/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:647359)
	at async /Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:622142
	at async C (/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:618648)
	at async t.resolveWithLocalServer (/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:621757)
	at async t.resolve (/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:644967)
	at async /Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.98.0/out/extension.js:1:720839
[12:21:41.961] ------

```

**Comment by Kira-Pilot** [comment]
@stirby to see if he can reproduce
