### ISSUE TITLE
bug: folder URI parameter with relative path fails to open silently

### ISSUE THREAD

**Issue by johnstcn** [coder/vscode-coder#80]
Trying to open a VSCode URI of the following format will fail _silently_ unless you bust open the VSCode DevTools and watch the error log:

```
vscode://coder.coder-remote/open?owner=john&workspace=joes-workspace&url=https%3A%2F%2Fdev.coder.com&token=supersecret&agent=smith&folder=relative%2Fpath
```

The error is:

```
Error: [UriError]: If a URI contains an authority component, then the path component must either be empty or begin with a slash ("/") character
	at T (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:23616)
	at new C (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:24703)
	at new E (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:26084)
	at C.from (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:66:25501)
	at t.Commands.<anonymous> (c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:154887)
	at Generator.next (<anonymous>)
	at c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:149762
	at new Promise (<anonymous>)
	at i (c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:149507)
	at t.Commands.open (c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:153240)
	at m.h (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:125797)
	at m.g (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:124687)
	at m.executeCommand (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:98:124587)
	at Object.executeCommand (c:\Users\agentsmith\AppData\Local\Programs\Microsoft VS Code\resources\app\out\vs\workbench\api\node\extensionHostProcess.js:114:23801)
	at c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:157816
	at Generator.next (<anonymous>)
	at i (c:\Users\agentsmith\.vscode\extensions\coder.coder-remote-0.1.16\dist\extension.js:1:156251)
```

Correct behaviour would probably be one of:
1) Complain loudly e.g. show an error dialog
2) Attempt to resolve the folder relative to `$HOME`

**Comment by matifali** [comment]
Hi @johnstcn should we close this as completed?

**Comment by johnstcn** [comment]
Fixed by https://github.com/coder/coder/pull/7120
