### ISSUE TITLE
receiving `WRONG_VERSION_NUMBER` when pasting API key into extension

### ISSUE THREAD

**Issue by ericpaulsen** [coder/vscode-coder#84]
using VS Code on a Windows Desktop, using latest version of Coder CLI & server, `0.22.2`. the session token input is the one received via the CLI auth flow:

![image](https://user-images.githubusercontent.com/9683576/233231621-f42d273b-a26b-4163-95da-ecaa8a8da1c4.png)

despite the invalid token, Coder continues to attempt the connection. the user is even able to see the directory. here's the log output:

```
[16:37:14.540] Running script with connection command: "C:\Program Files\Git\usr\bin\ssh.exe" -T -D 52895 "coder-vscode--<username>--first" bash 
[16:37:14.558] Terminal shell path: C:\WINDOWS\System32\cmd.exe
[16:37:16.415] > ssh: Could not resolve hostname coder-vscode--<username>--first: Name or service no > t known > ]0;C:\WINDOWS\System32\cmd.exe
[16:37:16.415] Got some output, clearing connection timeout
[16:37:16.429] > The process tried to write to a nonexistent pipe.
[16:37:17.812] "install" terminal command done
[16:37:17.813] Install terminal quit with output: t known
[16:37:17.813] Received install output: t known
[16:37:17.814] Failed to parse remote port from server output
[16:37:17.816] Resolver error: Error: at m.Create (c:\Users\nadendk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:584145) at t.handleInstallOutput (c:\Users\nadendk\.vscode\extensions\ms-vscode-remote.remote-ssh-0.100.0\out\extension.js:1:582705) at t.tryInstall (c:\Users\nadendk\.vscode\extensions\m
```

**Comment by ericpaulsen** [comment]
@kylecarbs @bpmct this seems to be a Windows-specific issue, as I confirmed with prospect that their macOS users are not seeing this behavior.

**Comment by matifali** [comment]
I regularly use windows and have never run into this
Are there any specific steps to reproduce?

**Comment by ericpaulsen** [comment]
@deansheather says this is likely proxy or cert related. I've followed up with the customer to check their proxy & certificate trust settings.

**Comment by ericpaulsen** [comment]
the VS Code proxy settings are the same as the Windows machine, and the Coder certificate is trusted. this is validated because they are able to connect via `coder login <https://domain.com>`.

**Comment by bpmct** [comment]
It's possible the VS Code extension does not respect `HTTP_PROXY`. @rodrimaia said he's looking into this today. #78

**Comment by ericpaulsen** [comment]
related #105

**Comment by matifali** [comment]
It cannot reproduce on Coder version 2.19.0 and extension 1.4.1
