### ISSUE TITLE
Connection timeouts (unable to connect)

### ISSUE THREAD

**Issue by bpmct** [coder/vscode-coder#85]
I'm using the VS Code Desktop button and am unable to connect:

Remote - SSH Output:

```sh
[08:55:24.525] Log Level: 2
[08:55:24.584] VS Code version: 1.77.3
[08:55:24.584] Remote-SSH version: remote-ssh@0.100.0
[08:55:24.584] darwin x64
[08:55:26.019] SSH Resolver called for "ssh-remote+coder-vscode--bpmct--dev", attempt 1
[08:55:26.019] "remote.SSH.useLocalServer": false
[08:55:26.020] "remote.SSH.showLoginTerminal": false
[08:55:26.020] "remote.SSH.remotePlatform": {"coder-vscode--bpmct--ben-stable":"linux","coder-vscode--bpmct--websites":"linux","coder-vscode--bpmct--backstage":"linux","coder-vscode--bpmct--vnc":"linux","coder-vscode--ben--my-workspace":"linux","coder-vscode--bpmct--projects":"linux","coder-vscode--ben--testing-permissions":"linux","coder-vscode--bpmct--hello1":"linux","coder-vscode--bpmct--workshop2":"linux","coder-vscode--bpmct--workshop":"linux","coder-vscode--bpmct--systemd-workshop":"linux","coder-vscode--bpmct--ben":"linux","coder-vscode--ben--test":"linux","coder-vscode--bpmct--dev":"linux","coder-vscode--bpmct--android":"linux","coder-vscode--bpmct--avd2":"linux","coder-vscode--ben--yipee":"linux","coder-vscode--ben--dev":"linux","coder-vscode--BrunoQuaresma--bruno-br":"linux"}
[08:55:26.020] "remote.SSH.path": undefined
[08:55:26.020] "remote.SSH.configFile": undefined
[08:55:26.020] "remote.SSH.useFlock": true
[08:55:26.021] "remote.SSH.lockfilesInTmp": false
[08:55:26.021] "remote.SSH.localServerDownload": auto
[08:55:26.021] "remote.SSH.remoteServerListenOnSocket": false
[08:55:26.021] "remote.SSH.showLoginTerminal": false
[08:55:26.021] "remote.SSH.defaultExtensions": []
[08:55:26.022] "remote.SSH.loglevel": 2
[08:55:26.022] "remote.SSH.enableDynamicForwarding": true
[08:55:26.022] "remote.SSH.enableRemoteCommand": false
[08:55:26.022] "remote.SSH.serverPickPortsFromRange": {}
[08:55:26.022] "remote.SSH.serverInstallPath": {}
[08:55:26.041] SSH Resolver called for host: coder-vscode--bpmct--dev
[08:55:26.041] Setting up SSH remote "coder-vscode--bpmct--dev"
[08:55:26.044] Using commit id "704ed70d4fd1c6bd6342c436f1ede30d1cff4710" and quality "stable" for server
[08:55:26.048] Install and start server if needed
[08:55:26.059] PATH: /usr/local/opt/openjdk/bin:/Users/benpotter/.gem/ruby/3.2.1/bin:/Users/benpotter/.rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/bin:/Users/benpotter/.rubies/ruby-3.2.1/bin:/Users/benpotter/.deno/bin:/Users/benpotter/.nvm/versions/node/v14.19.3/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/usr/local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/sbin/:/Users/benpotter/go/binATH=/Users/benpotter/.gem/ruby/3.2.1/bin:/Users/benpotter/.rubies/ruby-3.2.1/lib/ruby/gems/3.2.0/bin:/Users/benpotter/.rubies/ruby-3.2.1/bin:/Users/benpotter/.deno/bin:/Users/benpotter/.nvm/versions/node/v14.19.3/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/go/bin:/Library/Apple/usr/bin:/usr/local/bin:/Applications/Visual Studio Code.app/Contents/Resources/app/bin:/usr/local/sbin/:/Users/benpotter/go/bin:/Users/benpotter/Library/Android/sdk/emulator:/Users/benpotter/Library/Android/sdk/tools:/Users/benpotter/Library/Android/sdk/platform-tools
[08:55:26.060] Checking ssh with "ssh -V"
[08:55:26.066] > OpenSSH_9.0p1, LibreSSL 3.3.6

[08:55:26.071] Running script with connection command: ssh -T -D 56731 -o ConnectTimeout=15 'coder-vscode--bpmct--dev' bash
[08:55:43.074] Resolver error: Error: Connecting with SSH timed out
	at m.Timeout (/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:584271)
	at Timeout._onTimeout (/Users/benpotter/.vscode/extensions/ms-vscode-remote.remote-ssh-0.100.0/out/extension.js:1:680275)
	at listOnTimeout (node:internal/timers:559:17)
	at process.processTimers (node:internal/timers:502:7)
[08:55:43.087] ------
```

Extension output:
```sh
Found existing binary: /Users/benpotter/Library/Application Support/Code/User/globalStorage/coder.coder-remote/bin/coder-darwin-amd64
Using binName: coder-darwin-amd64
Using binPath: /Users/benpotter/Library/Application Support/Code/User/globalStorage/coder.coder-remote/bin/coder-darwin-amd64
Using ETag: 3b7a1d5aa822eb617912fc8ac3edacc25d263884
Response status code: 304
Using cached binary: /Users/benpotter/Library/Application Support/Code/User/globalStorage/coder.coder-remote/bin/coder-darwin-amd64
```

**Comment by bpmct** [comment]
I tried restarting my workspace. Sadly, still unable to connect.

**Comment by matifali** [comment]
Closing due to age and not reported by any other users. Please reopen or comment if the issue is seen again.
